bases/urls.py
from django.urls import path
from django.contrib.auth import views as login
from .views import Home 

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', login.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', login.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

cmp/urls.py
from django.urls import path
from .views import ProveedorView, ProveedorNew, ProveedorEdit, ProveedorDel

urlpatterns = [
    # Proveedores
    path('proveedores/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/new', ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedores/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/delete/<int:pk>', ProveedorDel.as_view(), name='proveedor_delete'),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
    MarcaView, MarcaNew, MarcaEdit, MarcaDel, MarcaInactivar, \
    ProductoView, ProductoNew, ProductoEdit, ProductoInactivar

urlpatterns = [
    # Categorias
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_delete'),

    # SubCategorias
    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_delete'),

    # Marcas
    path('marcas/', MarcaView.as_view(), name='marca_list'),
    path('marcas/new', MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/delete/<int:pk>', MarcaDel.as_view(), name='marca_delete'),
    path('marcas/inactivar/<int:pk>', MarcaInactivar.as_view(), name='marca_inactivar'),

    # Productos
    path('productos/', ProductoView.as_view(), name='producto_list'),
    path('productos/new', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:pk>', ProductoInactivar.as_view(), name='producto_inactivar'),

]

tareas/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include (('bases.urls','bases'), namespace='bases')),
    path('task/', include('task.urls'), name='task'),
    path('inv/', include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls','cmp'), namespace='cmp')),
]

task/urls.py
from django.urls import path
from .views import *

app_name = 'task'

urlpatterns = [
    path('list/', TaskView.as_view(), name='task_list'),
    #path('list/', task_list, name='task_list'),
    path('<int:pk>/', task_detail, name='task_detail'),
    path('create/', TaskCreate.as_view(), name='task_create'),
    #path('create/', task_create, name='task_create'),
    path('<int:pk>/edit/', TaskEdit.as_view(), name='task_edit'),
    #path('<int:pk>/edit/', task_edit, name='task_edit'),
    path('<int:pk>/delete/', TaskDelete.as_view(), name='task_delete'),
    #path('<int:pk>/delete/', task_delete, name='task_delete'),
    path('<int:pk>/complete/', task_complete, name='task_complete'),
    path('modal/', TaskModal.as_view(), name='task_modal'),
]


bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True) # Fecha de Creacion
    fm = models.DateTimeField(auto_now=True) # Fecha de Modificacion
    uc = models.ForeignKey(User, on_delete=models.CASCADE) # Usuario de Creacion
    um = models.IntegerField(blank=True, null=True) # Usuario de Modificacion

    class Meta:
        abstract = True # Para que no cree una tabla en la base de datos

bases/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin #para que solo los usuarios logueados puedan ver la pagina
from django.views.generic import TemplateView
# Create your views here.


class Home(LoginRequiredMixin, TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'
    

bases/templates/bases/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {% block title %}
    <title>Task</title>
    {% endblock %}

    <!-- Datatables -->
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/af-2.6.0/datatables.min.css" rel="stylesheet">

    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    
</head>
<body>
    <!-- Responsive navbar-->
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <a class="navbar-brand" href="#!">Mi Aplicación</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'bases:home' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'task:task_list' %}">Tareas</a></li>
                    
                    
                    <!-- inv -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Inventario
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'inv:categoria_list' %}">Categorias</a>
                            <a class="dropdown-item" href="{% url 'inv:subcategoria_list' %}">SubCategorias</a>
                            <a class="dropdown-item" href="{% url 'inv:marca_list' %}">Marcas</a>
                            <a class="dropdown-item" href="{% url 'inv:producto_list' %}">Productos</a>
                        </div>
                    </li>

                      <!-- cmp -->
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Compras
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'cmp:proveedor_list' %}">Proveedores</a>
                        </div>
                    </li>

                    <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Services</a></li>

                    <!-- login & logout-->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" 
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           Hola {{ user.username }} !!
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="#">Perfil</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'bases:logout'%}">Salir</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}

    <div class="container mb-5 p-2 shadow">
        {% block content %}

        {% endblock %}
        <br>
        {% block messages %}
            {% if messages %}
            <div class="alert alert-primary" role="alert">
                <ul class="messages">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>    
            </div>
            {% endif %}
        {% endblock %}
        
    </div>


    <!-- Footer-->
    {% block footer%}
    <footer class="py-5 bg-dark">
        <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; MyTask 2023</p></div>
    </footer>
    {% endblock %}
    
    <div class="modal fade" id="popup"></div>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>

    <!-- Ajax -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>    

    <!-- Datatables -->
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.8/af-2.6.0/datatables.min.js"></script>

    <!-- Jquery Confirm -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

    {% block js %}
    {% endblock %}
    
</body>

</html>

bases/templates/bases/home.html
{% extends 'bases/base.html' %}

{% block content %}
    {% load static %}
   <!-- Page Content-->
   <div class="container px-4 px-lg-5">
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static '/images/img1.jpg' %}" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">WFarel Developers</h1>
            <p>Mi código es más que líneas; es la esencia de la creatividad que impulsa la funcionalidad. Si buscas un arquitecto digital que no solo entienda tu visión, sino que la eleve a nuevas alturas, estás en el lugar correcto. Convierte lo imaginable en lo alcanzable, y hazlo con un toque de magia digital."</p>
            <a class="btn btn-primary" href="#!">Información</a>
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">"Construyendo el futuro, una línea de código a la vez."</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Desarrollo</h2>
                    <p class="card-text">Desarrollo web y de aplicaciones que superan expectativas.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Idea</h2>
                    <p class="card-text">Transformamos ideas en experiencias digitales excepcionales.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Pasión</h2>
                    <p class="card-text">Tu idea, nuestra pasión, una aplicación perfecta.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bases/templates/bases/login.html
{% extends 'bases/base.html' %}

{% block title %}{% endblock %}
{% block navbar %}{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4 offset-md-4 card shadow" >
                <h1>Login</h1>
                <hr>
                <form action="{% url 'bases:login' %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Login" class="btn btn-success btn-block">
                </form>
                <hr>
                
            </div>
        </div>
    </div>
{% endblock %}

{% block footer%}{% endblock %}