cmp/urls.py
from django.urls import path
from .views import ProveedorView, ProveedorNew, ProveedorEdit, ProveedorDel

urlpatterns = [
    # Proveedores
    path('proveedores/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/new', ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedores/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/delete/<int:pk>', ProveedorDel.as_view(), name='proveedor_delete'),
]

tareas/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include (('bases.urls','bases'), namespace='bases')),
    path('task/', include('task.urls'), name='task'),
    path('inv/', include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls','cmp'), namespace='cmp')),
]

task/urls.py
from django.urls import path
from .views import *

app_name = 'task'

urlpatterns = [
    path('list/', TaskView.as_view(), name='task_list'),
    #path('list/', task_list, name='task_list'),
    path('<int:pk>/', task_detail, name='task_detail'),
    path('create/', TaskCreate.as_view(), name='task_create'),
    #path('create/', task_create, name='task_create'),
    path('<int:pk>/edit/', TaskEdit.as_view(), name='task_edit'),
    #path('<int:pk>/edit/', task_edit, name='task_edit'),
    path('<int:pk>/delete/', TaskDelete.as_view(), name='task_delete'),
    #path('<int:pk>/delete/', task_delete, name='task_delete'),
    path('<int:pk>/complete/', task_complete, name='task_complete'),
    path('modal/', TaskModal.as_view(), name='task_modal'),
]


task/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    limit_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.title

task/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'complete')
        labels = {
            'title': 'Title',
            'description': 'Description',
            'complete': 'Complete',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }


task/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task
from .forms import TaskForm

# Create your views here.


class TaskModal(LoginRequiredMixin, CreateView):
    model = Task
    template_name = 'task/task_modal.html'
    context_object_name = 'tasks'
    form_class = TaskForm
    success_url = reverse_lazy('task:task_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.title = form.instance.title.upper()
        return super().form_valid(form)



class TaskView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'task/task_list.html'
    context_object_name = 'tasks'
    success_url = reverse_lazy('task:task_list')
    login_url = 'bases:login'
    ordering = ['complete']

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    template_name = 'task/task_modal.html'
    context_object_name = 'tasks'
    form_class = TaskForm
    success_url = reverse_lazy('task:task_list')
    login_url = 'bases:login'

    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.title = form.instance.title.upper()
        return super().form_valid(form)

class TaskEdit(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'task/task_modal.html'
    context_object_name = 'tasks'
    form_class = TaskForm
    success_url = reverse_lazy('task:task_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.title = form.instance.title.upper()
        return super().form_valid(form) 

class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'task/task_delete.html'
    context_object_name = 'tasks'
    success_url = reverse_lazy('task:task_list')
    login_url = 'bases:login'

def task_detail(request, pk):
    task = get_object_or_404(Task, pk=pk)
    return render(request, 'task:task_detail', {'task': task})

def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('task:task_list')
    else:
        form = TaskForm()
    return render(request, 'task/task_create.html', {'form': form})

def task_edit(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task:task_list')
    else:
        form = TaskForm(instance=task)
    return render(request, 'task/task_edit.html', {'form': form})

def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.delete()
    return redirect('task:task_list')

def task_complete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.complete = True
    task.save()
    return redirect('task:task_list')
    

task/templates/task/home.html
{% extends 'task/base.html' %}

{% block content %}

   <!-- Page Content-->
   <div class="container px-4 px-lg-5">
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">Business Name or Tagline</h1>
            <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
            <a class="btn btn-primary" href="#!">Call to Action!</a>
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Card One</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Card Two</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex natus at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore voluptates quos eligendi labore.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Card Three</h2>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                </div>
                <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

task/templates/task/task_create.html
{% extends 'bases/base.html' %}

{% block content %}
<div class="container p-3 col-md-4 col-offset-4">
    <h2>Crear Tarea</h2>
    <form action="" method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        
        <div class="dropdown-divider"></div>
        
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="{% url 'task:task_list' %}" class="btn btn-secondary">Cancelar</a>
        
    </form>
</div>

{% endblock %}

task/templates/task/task_delete.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}{% endblock %}


{% block content %}

<div class="container p-3 col-md-4 col-offset-4">
    
    <h1>Eliminar Tarea</h1>
    <form action="" method="post">
        {% csrf_token %}
        Desea eliminar la tarea {{ tasks.title }}?
        <div class="dropdown-divider"></div>
        <div class="text-center">
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-primary" href="{% url 'task:task_list' %}">Cancelar</a>
        </div>
        
    </form>

</div>


{% endblock %}

task/templates/task/task_edit.html
{% extends 'bases/base.html' %}
{% block title %}{% endblock %}


{% block content %}
<div class="container p-3 col-md-4 col-offset-4">
    <h2>Editar Tarea</h2>
    <form action="" method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        
        <div class="dropdown-divider"></div>
        
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="{% url 'task:task_list' %}" class="btn btn-secondary">Cancelar</a>
        
    </form>
</div>

{% endblock %}

task/templates/task/task_list.html

{% extends 'bases/base.html' %}

{% block content %}
    <div class="container">
             <!-- Button trigger modal -->
             <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-extra="hola"
                onclick="abrirModal('{% url 'task:task_create' %}')">
                Nueva tarea
            </button>
        
        <div class="container p-3 pb-4 my-3 bg-dark text-white">
            Tareas  
            <a class="btn btn-primary btn-sm float-right"  href="{% url 'task:task_create' %}">Nueva tarea</a>
            
        </div>
             
        <div class="row">
            {% if tasks %}
                {% for task in tasks %}
                    <div class="col-md-6 mb-3">
                        <div class="card h-100">
                            <div class="card-body">
                                <h4 class="card-title">{{ task.title }}</h4>
                                <p class="card-text">{{ task.description }}.</p>
                                <p>{{ task.created }}</p>
                                
                            </div>
                            <div class="card-footer">
                                {% if task.complete %}
                                    <div style="color: green;">Tarea completada</div>
                                {% else %}
                                    <a class="btn btn-warning btn-sm" href="{% url 'task:task_edit' task.id %}">Editar</a>
                                    <a class="btn btn-danger btn-sm" href="{% url 'task:task_delete' task.id %}">Eliminar</a>
                                    <a class="btn btn-primary btn-sm" href="{% url 'task:task_complete' task.id %}">Completado</a>
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
                                    onclick="abrirModal('{% url 'task:task_edit' task.id %}')">
                                    editar tarea
                                </button>
                                    
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No hay tareas</p>
            {% endif %}
        </div>

   
        
        

    </div>

{% endblock %}


task/templates/task/task_modal.html
<!-- Modal -->
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        
        <div class="modal-body">
            {% if obj %}
            <form action="{%url 'task:task_edit' obj.pk %}" method="post" role="form"  id="form1">
            {% else %}
            <form action="{%url 'task:task_create' %}" method="post" role="form" id="form1" >
                console.log(obj);
            {% endif %}
            
                {% csrf_token %}
                {{ form.as_p }}

            </form>
        </div>
        <div class="modal-footer">
        
            <button type="button" class="btn btn-primary" onclick="enviarFormulario(form1)">Save changes</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="cerrarModal()">Close</button>
        
        </div>
    </div>
</div>