cmp/urls.py
from django.urls import path
from .views import ProveedorView, ProveedorNew, ProveedorEdit, ProveedorDel

urlpatterns = [
    # Proveedores
    path('proveedores/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/new', ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedores/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/delete/<int:pk>', ProveedorDel.as_view(), name='proveedor_delete'),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
    MarcaView, MarcaNew, MarcaEdit, MarcaDel, MarcaInactivar, \
    ProductoView, ProductoNew, ProductoEdit, ProductoInactivar

urlpatterns = [
    # Categorias
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_delete'),

    # SubCategorias
    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_delete'),

    # Marcas
    path('marcas/', MarcaView.as_view(), name='marca_list'),
    path('marcas/new', MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/delete/<int:pk>', MarcaDel.as_view(), name='marca_delete'),
    path('marcas/inactivar/<int:pk>', MarcaInactivar.as_view(), name='marca_inactivar'),

    # Productos
    path('productos/', ProductoView.as_view(), name='producto_list'),
    path('productos/new', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:pk>', ProductoInactivar.as_view(), name='producto_inactivar'),

]

tareas/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include (('bases.urls','bases'), namespace='bases')),
    path('task/', include('task.urls'), name='task'),
    path('inv/', include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls','cmp'), namespace='cmp')),
]

inv/models.py
from django.db import models

from bases.models import ClaseModelo
# Create your models here.

class Categoria(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        # help_text='Descripcion de la Categoria',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = 'Categorias'

class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        # help_text='Descripcion de la SubCategoria',
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural = 'Sub Categorias'
        unique_together = ('categoria', 'descripcion')

class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        # help_text='Descripcion de la Marca',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = 'Marcas'

class Producto(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(
        max_length=50,
        blank=True,
        null=True
    )
    descripcion = models.CharField(
        max_length=200,
        # help_text='Descripcion del Producto',
    )
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural = 'Productos'
        unique_together = ('codigo', 'codigo_barra')

inv/forms.py
from django import forms
from .models import Categoria, SubCategoria, Marca, Producto

# validar que no se repita la descripcion del proveedor


#Clase para el formulario de Categoria
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripcion de la categoria', 'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})

    # validar que no se repita la descripcion del Categoria
    def clean(self):
        try:
            sc = Categoria.objects.get(descripcion=self.cleaned_data['descripcion'].upper())
            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError('Registro ya existe')
            elif self.instance.pk != sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError('Cambio no permitido')
        except Categoria.DoesNotExist:
            pass
        return self.cleaned_data
     

#Clase para el formulario de SubCategoria
class SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True).order_by('descripcion')
    )
    class Meta:
        model = SubCategoria
        fields = ['categoria', 'descripcion', 'estado']
        labels = {'descripcion':'Descripcion de la subcategoria', 'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['categoria'].empty_label = 'Seleccione Categoria'
        self.fields['categoria'].widget.attrs['class'] = 'form-control select2'
        self.fields['descripcion'].widget.attrs['class'] = 'form-control'
    
    # validar que no se repita la descripcion del SubCategoria
    def clean(self):
        try:
            sc = SubCategoria.objects.get(descripcion=self.cleaned_data['descripcion'].upper())
            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError('Registro ya existe')
            elif self.instance.pk != sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError('Cambio no permitido')
        except SubCategoria.DoesNotExist:
            pass
        return self.cleaned_data


#Clase para el formulario de Marca            
class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripcion de la marca', 'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) 
        self.fields['descripcion'].widget.attrs['class'] = 'form-control'

    # validar que no se repita la descripcion del Marca
    def clean(self):
        try:
            sc = Marca.objects.get(descripcion=self.cleaned_data['descripcion'].upper())
            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError('Registro ya existe')
            elif self.instance.pk != sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError('Cambio no permitido')
        except Marca.DoesNotExist:
            pass
        return self.cleaned_data


#Clase para el formulario de Producto
class ProductoForm(forms.ModelForm):
    subcategoria = forms.ModelChoiceField(
        queryset=SubCategoria.objects.filter(estado=True).order_by('descripcion')
    )
    marca = forms.ModelChoiceField(
        queryset=Marca.objects.filter(estado=True).order_by('descripcion')
    )
    class Meta:
        model = Producto
        fields = ['codigo', 'codigo_barra', 'descripcion', 'estado', 'precio', 'existencia', 'ultima_compra', 'marca', 'subcategoria']
        exclude = ['usuario_modificacion', 'fecha_modificacion']
        labels = {'descripcion':'Descripcion del producto', 'estado':'Estado', 'precio':'Precio', 'existencia':'Existencia', 'ultima_compra':'Ultima Compra', 'marca':'Marca', 'subcategoria':'Subcategoria'}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) 
        self.fields['codigo'].widget.attrs['autofocus'] = True
        self.fields['codigo'].widget.attrs['class'] = 'form-control'
        self.fields['codigo_barra'].widget.attrs['class'] = 'form-control'
        self.fields['descripcion'].widget.attrs['class'] = 'form-control'
        self.fields['estado'].widget.attrs['class'] = 'form-control'
        self.fields['precio'].widget.attrs['class'] = 'form-control'
        self.fields['existencia'].widget.attrs['class'] = 'form-control'
        self.fields['ultima_compra'].widget.attrs['class'] = 'form-control'
        self.fields['marca'].widget.attrs['class'] = 'form-control'
        self.fields['subcategoria'].widget.attrs['class'] = 'form-control'
    
    # validar que no se repita la descripcion del Producto
    def clean(self):
        try:
            sc = Producto.objects.get(codigo=self.cleaned_data['codigo'].upper())
            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError('Registro ya existe')
            elif self.instance.pk != sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError('Cambio no permitido')
        except Producto.DoesNotExist:
            pass
        return self.cleaned_data

inv/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Categoria, SubCategoria, Marca, Producto
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, ProductoForm
from django.urls import reverse_lazy
# Create your views here.

# Categoria

class CategoriaView(LoginRequiredMixin, ListView):
    model = Categoria
    template_name = 'inv/categoria_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

class CategoriaNew(LoginRequiredMixin, CreateView):
    model = Categoria
    template_name = 'inv/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    
class CategoriaEdit(LoginRequiredMixin, UpdateView):
    model = Categoria
    template_name = 'inv/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
    
class CategoriaDel(LoginRequiredMixin, DeleteView):
    model = Categoria
    extra_context = {'clase': 'Categoria', 'pag_anterior': 'inv:categoria_list'}
    template_name = 'inv/catalogos_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:categoria_list')
    login_url = 'bases:login'

# SubCategoria

class SubCategoriaView(LoginRequiredMixin, ListView):
    model = SubCategoria
    template_name = 'inv/subcategoria_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

class SubCategoriaNew(LoginRequiredMixin, CreateView):
    model = SubCategoria
    template_name = 'inv/subcategoria_form.html'
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_url = reverse_lazy('inv:subcategoria_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class SubCategoriaEdit(LoginRequiredMixin, UpdateView):
    model = SubCategoria
    template_name = 'inv/subcategoria_form.html'
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_url = reverse_lazy('inv:subcategoria_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class SubCategoriaDel(LoginRequiredMixin, DeleteView):
    model = SubCategoria
    extra_context = {'clase': 'SubCategoria', 'pag_anterior': 'inv:subcategoria_list'}
    template_name = 'inv/catalogos_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:subcategoria_list')
    login_url = 'bases:login'

# Marca
    
class MarcaView(LoginRequiredMixin, ListView):
    model = Marca
    template_name = 'inv/marca_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

class MarcaNew(LoginRequiredMixin, CreateView):
    model = Marca
    template_name = 'inv/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy('inv:marca_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class MarcaEdit(LoginRequiredMixin, UpdateView):
    model = Marca
    template_name = 'inv/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy('inv:marca_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class MarcaDel(LoginRequiredMixin, DeleteView):
    model = Marca
    template_name = 'inv/catalogos_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:marca_list')
    login_url = 'bases:login'

class MarcaInactivar(LoginRequiredMixin, DeleteView):
    model = Marca
    template_name = 'inv/catalogos_mod.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:marca_list')
    login_url = 'bases:login'

    def post(self, request, *args, **kwargs):
        object = self.get_object()
        object.estado = False
        object.save()
        return redirect('inv:marca_list')
    
# Producto
    
class ProductoView(LoginRequiredMixin, ListView):
    model = Producto
    template_name = 'inv/producto_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

class ProductoNew(LoginRequiredMixin, CreateView):
    model = Producto
    template_name = 'inv/producto_form.html'
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy('inv:producto_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        form.instance.codigo = form.instance.codigo.upper()
        return super().form_valid(form)

class ProductoEdit(LoginRequiredMixin, UpdateView):
    model = Producto
    template_name = 'inv/producto_form.html'
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy('inv:producto_list')
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        form.instance.codigo = form.instance.codigo.upper()
        return super().form_valid(form)

class ProductoInactivar(LoginRequiredMixin, DeleteView):
    model = Producto
    template_name = 'inv/catalogos_mod.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:producto_list')
    login_url = 'bases:login'

    def post(self, request, *args, **kwargs):
        object = self.get_object()
        object.estado = False
        object.save()
        return redirect('inv:producto_list')

inv/templates/inv/catalogos_del.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}{% endblock %}


{% block content %}

<div class="container p-3 col-md-4 col-offset-4">

    <h1>Eliminar Categoria</h1>
    <form action="" method="post">
        {% csrf_token %}
        Desea eliminar la categoria {{ obj.descripcion }}?
        <div class="dropdown-divider"></div>
        <div class="text-center">
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-primary" href="{% url 'inv:categoria_list' %}">Cancelar</a>
        </div>
        
    </form>

</div>


{% endblock %}

inv/templates/inv/catalogos_mod.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}{% endblock %}


{% block content %}

<div class="container p-3 col-md-4 col-offset-4">

    <h1>Inactivar??</h1>
    <form action="" method="post">
        {% csrf_token %}
        Desea inactivar {{ obj.descripcion }}?
        <div class="dropdown-divider"></div>
        <div class="text-center">
            <button class="btn btn-danger" type="submit">Inactivar</button>
            <a class="btn btn-primary" href="">Cancelar</a>
        </div>
        
    </form>

</div>

{% endblock %}

inv/templates/inv/categoria_form.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}{% endblock %}


{% block content %}

<div class="container p-3 col-md-4 col-offset-4">

    {% if not obj %}
    <h1>Crear Categoria</h1>
    {% else %}
    <h1>Editar Categoria</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="dropdown-divider"></div>
        <div class="text-center">
            <input class="btn btn-success" type="submit" value="Guardar">
        <a class="btn btn-danger" href="{% url 'inv:categoria_list' %}">Cancelar</a>
        </div>
        
    </form>

</div>


{% endblock %}

inv/templates/inv/categoria_list.html
{% extends "bases/base.html" %}

{% block title %}
<title>Categorias</title>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="container p-3 pb-4 my-3 bg-dark text-white">
            Categorias  
            <a class="btn btn-primary btn-sm float-right"  href="{% url 'inv:categoria_new' %}">Nueva</a>
        </div>
        
        {% if not obj %}
        <p>No hay Categorias</p>
        {% else %}
        <table class="table table-hover table-striped" id="categoria">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Descripcion</th>
                    <th>Estado</th>
                    <th>F. Creado</th>
                    <th>F. Modif.</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{% if item.estado %}
                        <span class="label label-success">Activo</span>
                        {% else %}
                        <span class="label label-danger">Inactivo</span>
                        {% endif %}
                    </td>
                    <td>{{ item.fc|date:"d/m/Y H:i" }}</td>
                    <td>{{ item.fm|date:"d/m/Y H:i" }}</td>
                    <td>
                        <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-sm">Editar</a>
                        <a href="{% url 'inv:categoria_delete' item.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $('#categoria').DataTable(
        {
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por pagina",
                "zeroRecords": "No se encontro registros",
                "info": "Mostrando pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                "search": "Buscar",
                "paginate": {
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            }
        }
    );
</script>
{% endblock %}

inv/templates/inv/marca_form.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}{% endblock %}


{% block content %}

<div class="container p-3 col-md-4 col-offset-4">

    {% if not obj %}
    <h1>Crear Marca</h1>
    {% else %}
    <h1>Editar Marca</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="dropdown-divider"></div>
        <div class="text-center">
            <input class="btn btn-success" type="submit" value="Guardar">
        <a class="btn btn-danger" href="{% url 'inv:marca_list' %}">Cancelar</a>
        </div>
        
    </form>

</div>


{% endblock %}

inv/templates/inv/marca_list.html
{% extends "bases/base.html" %}

{% block title %}
<title>Marcas</title>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="container p-3 pb-4 my-3 bg-dark text-white">
            Marcas
            <a class="btn btn-primary btn-sm float-right"  href="{% url 'inv:marca_new' %}">Nueva</a>
        </div>
        
        {% if not obj %}
        <p>No hay Marcas</p>
        {% else %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Descripcion</th>
                    <th>Estado</th>
                    <th>F. Creado</th>
                    <th>F. Modif.</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{% if item.estado %}
                        <span class="label label-success">Activo</span>
                        {% else %}
                        <span class="label label-danger">Inactivo</span>
                        {% endif %}
                    </td>
                    <td>{{ item.fc|date:"d/m/Y H:i" }}</td>
                    <td>{{ item.fm|date:"d/m/Y H:i" }}</td>
                    <td>
                        <a href="{% url 'inv:marca_edit' item.id %}" class="btn btn-warning btn-sm">Editar</a>
                        <a href="{% url 'inv:marca_delete' item.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                        <a href="{% url 'inv:marca_inactivar' item.id %}" class="btn btn-dark btn-sm">Inactivar</a>
                        
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

inv/templates/inv/producto_list.html
{% extends "bases/base.html" %}

{% block title %}
<title>Productos</title>  
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="container p-3 pb-4 my-3 bg-dark text-white">
            Productos
            <a class="btn btn-primary btn-sm float-right"  href="{% url 'inv:producto_new' %}">Nueva</a>
        </div>
        
        {% if not obj %}
        <p>No hay Productos</p>
        {% else %}
        <table class="table table-hover table-striped" id="tProducto">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Codigo</th>
                    <th>Codigo de barra</th>

                    <th>Descripcion</th>
                    <th>Precio</th>
                    <th>Stock</th>

                    <th>Ultima Compra</th>
                    <th>Subcategoria</th>
                    <th>Marca</th>                    

                    <th>Estado</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.codigo }}</td>
                    <td>{{ item.codigo_barra }}</td>

                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.precio }}</td>
                    <td>{{ item.existencia }}</td>

                    <td>{{ item.ultima_compra|date:"d/m/Y H:i" }}</td>
                    <td>{{ item.subcategoria }}</td>
                    <td>{{ item.marca }}</td>

                    <td>{% if item.estado %}
                        <span class="label label-success">Activo</span>
                        {% else %}
                        <span class="label label-danger">Inactivo</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'inv:producto_edit' item.id %}" class="btn btn-warning btn-sm">Editar</a>
                        <a href="{% url 'inv:producto_inactivar' item.id %}" class="btn btn-dark btn-sm">Inactivar</a>
                        
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $('#tProducto').DataTable(
        {
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por pagina",
                "zeroRecords": "No se encontro registros",
                "info": "Mostrando pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                "search": "Buscar",
                "paginate": {
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            }
        }
    );
</script>
{% endblock %}

inv/templates/inv/subcategoria_list.html
{% extends "bases/base.html" %}

{% block title %}
<title>SubCategoria</title>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="container p-3 pb-4 my-3 bg-dark text-white">
            SubCategorias  
            <a class="btn btn-primary btn-sm float-right"  href="{% url 'inv:subcategoria_new' %}">Nueva</a>
        </div>
        
        {% if not obj %}
        <p>No hay SubCategorias</p>
        {% else %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Descripcion</th>
                    <th>Categoria</th>
                    <th>Estado</th>
                    <th>F. Creado</th>
                    <th>F. Modif.</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.categoria }}</td>
                    <td>{% if item.estado %}
                        <span class="label label-success">Activo</span>
                        {% else %}
                        <span class="label label-danger">Inactivo</span>
                        {% endif %}
                    </td>
                    <td>{{ item.fc|date:"d/m/Y H:i" }}</td>
                    <td>{{ item.fm|date:"d/m/Y H:i" }}</td>
                    <td>
                        <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-sm">Editar</a>
                        <a href="{% url 'inv:subcategoria_delete' item.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}