cmp/urls.py
from django.urls import path
from .views import ProveedorView, ProveedorNew, ProveedorEdit, ProveedorDel

urlpatterns = [
    # Proveedores
    path('proveedores/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/new', ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedores/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/delete/<int:pk>', ProveedorDel.as_view(), name='proveedor_delete'),
]

tareas/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include (('bases.urls','bases'), namespace='bases')),
    path('task/', include('task.urls'), name='task'),
    path('inv/', include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls','cmp'), namespace='cmp')),
]

cmp/models.py
from django.db import models
from bases.models import ClaseModelo

# Create your models here.

class Proveedor(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
       # help_text='Descripción del proveedor',
        unique=True
    )
    direccion = models.CharField(
        max_length=250,
        null=True,
        blank=True
    )
    telefono = models.CharField(
        max_length=20,
        null=True,
        blank=True
    )
    email = models.CharField(
        max_length=250,
        null=True,
        blank=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Proveedor, self).save()

    class Meta:
        verbose_name_plural = 'Proveedores'

cmp/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = ['descripcion','direccion','telefono','email']
        labels = {'descripcion':'Descripcion del Proveedor','direccion':'Direccion','telefono':'Telefono','email':'Correo Electronico'}
        widget = {'descripcion':forms.TextInput(),'direccion':forms.TextInput(),'telefono':forms.TextInput(),'email':forms.TextInput()}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            #print(field)
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
    
    # validar que no se repita la descripcion del proveedor
    def clean(self):
        try:
            sc = Proveedor.objects.get(descripcion=self.cleaned_data['descripcion'].upper())
            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError('Registro ya existe')
            elif self.instance.pk != sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError('Cambio no permitido')
        except Proveedor.DoesNotExist:
            pass
        return self.cleaned_data
    

    
    

cmp/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin as SMM
from django.contrib.auth.mixins import PermissionRequiredMixin as PRM
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Proveedor
from .forms import ProveedorForm

# Create your views here.

class ProveedorView(LoginRequiredMixin, ListView):
    model = Proveedor
    template_name = 'cmp/proveedor_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

class ProveedorNew(SMM, LoginRequiredMixin, CreateView):
    model = Proveedor
    template_name = 'cmp/proveedor_form.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_url = reverse_lazy('cmp:proveedor_list')
    login_url = 'bases:login'
    success_message = 'Proveedor creado exitosamente.'
   
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class ProveedorEdit(SMM, LoginRequiredMixin, UpdateView):
    model = Proveedor
    template_name = 'cmp/proveedor_form.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_url = reverse_lazy('cmp:proveedor_list')
    login_url = 'bases:login'
    success_message = 'Proveedor actualizado exitosamente.'
    
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ProveedorDel(SMM, PRM, LoginRequiredMixin, DeleteView):
    model = Proveedor
    template_name = 'cmp/catalogos_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('cmp:proveedor_list')
    extra_context = {'clase': 'Proveedor', 'pag_anterior': 'cmp:proveedor_list'}
    login_url = 'bases:login'
    permission_required = 'cmp.delete_proveedor'
    success_message = 'Proveedor eliminado exitosamente.'

cmp/templates/cmp/catalogos_del.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}{% endblock %}


{% block content %}

<div class="container p-3 col-md-4 col-offset-4">

    <h1>{{clase}}</h1>
    <form action="" method="post">
        {% csrf_token %}
        Desea eliminar la {{clase}} {{ obj.descripcion }}?
        <div class="dropdown-divider"></div>
        <div class="text-center">
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-primary" href="{% url pag_anterior %}">Cancelar</a>
        </div>
        
    </form>

</div>


{% endblock %}

cmp/templates/cmp/proveedor_form.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}{% endblock %}


{% block content %}

<div class="container p-3 col-md-4 col-offset-4">

    {% if not obj %}
    <h1>Crear Proveedor</h1>
    {% else %}
    <h1>Editar Proveedor</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="dropdown-divider"></div>
        <div class="text-center">
            <input class="btn btn-success" type="submit" value="Guardar">
        <a class="btn btn-danger" href="{% url 'cmp:proveedor_list' %}">Cancelar</a>
        </div>
        
    </form>

</div>


{% endblock %}

cmp/templates/cmp/proveedor_list.html
{% extends "bases/base.html" %}

{% block title %}
<title>Proveedores</title>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="container p-3 pb-4 my-3 bg-dark text-white">
            Proveedores  
            <a class="btn btn-primary btn-sm float-right"  href="{% url 'cmp:proveedor_new' %}">Nueva</a>
        </div>
        
        {% if not obj %}
        <p>No hay Proveedores</p>
        {% else %}
        <table class="table table-hover table-striped" id="mProveedor">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Descripcion</th>
                    <th>Direccion</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.direccion }}</td>
                    <td>{{ item.telefono }}</td>
                    <td>{{ item.email }}</td>
                    <td>
                        <a href="{% url 'cmp:proveedor_edit' item.id %}" class="btn btn-warning btn-sm">Editar</a>
                        <a href="{% url 'cmp:proveedor_delete' item.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $('#mProveedor').DataTable(
        {
            "language": {
                "lengthMenu": "Mostrar _MENU_ registros por pagina",
                "zeroRecords": "No se encontro registros",
                "info": "Mostrando pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                "search": "Buscar",
                "paginate": {
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            }
        }
    );
</script>
{% endblock %}